name: update-oceano

on:
  schedule:
    # * is a special character in YAML so you have to quote this string - change cron string to '0 * 7 * *' to run once on the 7th day of the month
    - cron:  '0 * 7 * *'
  #push:
  #  branches: [ master ]
  workflow_dispatch:
  
jobs:    
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: bdbest/cinms:1.0 # docker image
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: clone repo
        run: git clone --depth 1 https://github.com/${{ github.repository }}.git .; ls
      - name: update infographiqR
        run: Rscript -e 'remotes::install_github("marinebon/infographiqR")'
      - name: update onmsR
        run: Rscript -e 'remotes::install_github("noaa-onms/onmsR")'        
      - name: update_oceano-data
        run: Rscript scripts/update_oceano-data.R
      - name: render_oceano-modals
        run: Rscript scripts/render_oceano-modals.R
      - name: commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}          
          git add -A
          git commit -a -m "changes from workflow **${{ github.workflow }}** [ci skip]"
          git push 
